{% set name = "reference-handler" %}
{% set version = "0.9.2" %}
{% set sha256 = "17bddc699a0ba1fd39d8b515248ea55c5f729462819447f5a82d5d563b51ff66" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/r/reference-handler/reference_handler-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - bibtexparser <2
    - python >=3.7

test:
  imports:
    - reference_handler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MolSSI/reference_handler
  summary: 'A Python package for creating a consolidated list of references (BibTex, RIS).'
  license: BSD-3-Clause
  license_file: LICENSE
extra:
  recipe-maintainers:
    - paulsaxe
